name: HTTYS build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: NodeJS ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure git credentials
        run: |
          git config --global user.email "dmitri.mcguckin26@gmail.com"
          git config --global user.name "Dmitri McGuckin"
      - name: Switch to build branch
        run: git checkout -B build

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Build
        run: ng build --prod

      - name: Strip repo to build only
        run: |
          mv dist/ ..
          rm -rf *
          mv ../dist/httys/* .
          rm -rf ../dist

      - run: git add -A
      - run: git commit -am "Website Build"
      - name: Delete `build` if already exists
        run: |
          if [[ -n "$(git ls-remote --heads origin build)" ]]; then
            git push origin --delete build
          fi
      - run: git push origin build
